### ISSUE TITLE
Add Final keyword

### ISSUE THREAD

**Issue by Y00ujin** [InFrame-dev/InFrame-iOS#107]
전체 클래스 또는 일부가 상속되지 않는 클래스 앞에는 `final 키워드`를 작성하는 건 어떨까요?
`vtable`을 거치지 않고 직접적으로 호출되기 때문에 성능상 더 좋은 퍼포먼스를 낼 수 있다고 하네요.

`final class ChoosePictureViewController: UIViewController { ... }`

> 관련 자료 함께 첨부해드려요!
> https://velog.io/@ryan-son/Swift-final-%ED%82%A4%EC%9B%8C%EB%93%9C-%EC%99%9C-%EC%82%AC%EC%9A%A9%ED%95%98%EB%8A%94%EA%B1%B8%EA%B9%8C

**Comment by yjnoh1016** [comment]
`final` 키워드가 성능 향상에 도움을 준다는 건 오늘 처음 알게 된 사실이네요!!
작성하는 방향이 좋을 것 같아요. 좋은 의견 감사합니다 😊
